// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnV7CFLoXos97OFuw88MXZRnmMllF1ZyA',
    appId: '1:1089643163003:web:7fefe760d45113337061de',
    messagingSenderId: '1089643163003',
    projectId: 'instagramclone-abd23',
    authDomain: 'instagramclone-abd23.firebaseapp.com',
    storageBucket: 'instagramclone-abd23.appspot.com',
    measurementId: 'G-5F0RF1H3L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9pqr8mb3QRZK5eaEtNvITD5P01lxIRDo',
    appId: '1:1089643163003:android:4a162321856f86077061de',
    messagingSenderId: '1089643163003',
    projectId: 'instagramclone-abd23',
    storageBucket: 'instagramclone-abd23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-2MBroQnvSb9ZfrknpFUHh1Hl6jdkyMA',
    appId: '1:1089643163003:ios:0b36cc7864d387987061de',
    messagingSenderId: '1089643163003',
    projectId: 'instagramclone-abd23',
    storageBucket: 'instagramclone-abd23.appspot.com',
    iosClientId: '1089643163003-ljeaprfnkhqi0evv7rrjgm7q8lvbscm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-2MBroQnvSb9ZfrknpFUHh1Hl6jdkyMA',
    appId: '1:1089643163003:ios:3256bf0892cfd0b97061de',
    messagingSenderId: '1089643163003',
    projectId: 'instagramclone-abd23',
    storageBucket: 'instagramclone-abd23.appspot.com',
    iosClientId: '1089643163003-1jp3gbgi4jbu24ove36gcm959pqlbfke.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
